#ifndef AWEEPROM_H
#define AWEEPROM_H

#define EEPROM_MAGIC 0x10
// "AuroraWatch v1.0"

#define EEPROM_HMAC_KEY 0x20
#define EEPROM_HMAC_KEY_SIZE 16

#define EEPROM_SITE_ID (EEPROM_HMAC_KEY + EEPROM_HMAC_KEY_SIZE)
#define EEPROM_SITE_ID_SIZE 2

#define EEPROM_ADC_ADDRESS_LIST (EEPROM_SITE_ID +  EEPROM_SITE_ID_SIZE)
#define EEPROM_ADC_ADDRESS_LIST_SIZE 3

#define EEPROM_ADC_CHANNEL_LIST (EEPROM_ADC_ADDRESS_LIST + EEPROM_ADC_ADDRESS_LIST_SIZE)
#define EEPROM_ADC_CHANNEL_LIST_SIZE 3

#define EEPROM_SD_SELECT (EEPROM_ADC_CHANNEL_LIST+EEPROM_ADC_CHANNEL_LIST_SIZE)
#define EEPROM_SD_SELECT_SIZE 1

#define EEPROM_USE_SD (EEPROM_SD_SELECT + EEPROM_SD_SELECT_SIZE)
#define EEPROM_SD_SELECT_SIZE 1

#endif
