name: Build AuroraWatchNet operation manuals

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_reusable-make-docs.yaml
    with:
      publish_to_github: true
